### ==========================================================================
### INPUT
### ==========================================================================
input type:keyboard {
    xkb_layout fr
    xkb_variant azerty
    xkb_numlock enabled
}
