### ==========================================================================
### STARTUP
### ==========================================================================

exec_always eww daemon
exec_always eww open bar

exec_always swaybg -i ~/Pictures/wallpaper.jpg -m fill
exec_always numlockx on