# =========================
# BASIC APPEARANCE
# =========================

set $bg #141414
set $accent #00ff41
set $border #3F3F3F
set $text #00ff41
set $alert #FF0000

font pango:JetBrainsMono Nerd Font 13

client.focused          $accent $accent $bg $text $accent
client.unfocused        $border $bg $border $text $border
client.urgent           $alert $alert $bg $text $alert

default_border pixel 1
gaps inner 8
gaps outer 4
