for_window [app_id="launcher"] floating enable, move position center, resize set 800 400

for_window [app_id="sway-cheatsheet"] floating enable, sticky enable, resize set 900 600, move position center